### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by ayarnell** [AlanCFleming82/AlanCFleming82.github.io#5]
Include CC license info

**Comment by AlanCFleming82** [comment]
Here is the HTML for the CC license
[CC license button.txt](https://github.com/AlanCFleming82/AlanCFleming82.github.io/files/3751884/CC.license.button.txt)

**Comment by AlanCFleming82** [comment]
I have added a satisfactory footer to the index page (and I prefer it just showing up on that one page).
