### ISSUE TITLE
Add paypal link

### ISSUE THREAD

**Issue by ayarnell** [AlanCFleming82/AlanCFleming82.github.io#6]

**Comment by AlanCFleming82** [comment]
Here is the HTML for the paypal button:

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_donations" />
<input type="hidden" name="business" value="AVH2HDZWQPUXS" />
<input type="hidden" name="currency_code" value="USD" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1" />
</form>

**Comment by AlanCFleming82** [comment]
Attached should be the HTML for the paypal button 
[paypalbutton.txt](https://github.com/AlanCFleming82/AlanCFleming82.github.io/files/3751865/paypalbutton.txt)
